; Upload ArduinoISP sketch to an Arduino Uno so it can act as an ISP programmer.
; Run from this folder:
;   pio run -t upload
;
; After this finishes, return to the parent folder and run the ATtiny build there.

[env:arduinoisp_uno]
platform = atmelavr
board = uno
framework = arduino
upload_port = /dev/tty.usbmodem11301
monitor_speed = 19200
