; PlatformIO Project Configuration File
; STC8G1K08 + 72x40 OLED duck animation
; https://docs.platformio.org/en/latest/boards/intel_mcs51/STC8G1K08.html

[env:STC8G1K08]
platform = intel_mcs51
board = STC8G1K08
upload_port = /dev/tty.usbmodem11101
upload_flags =
    -b
    9600
board_build.f_cpu = 11059200L

; Arduino blank sketch upload (temporary)
[env:arduino_blank]
platform = atmelavr
board = uno
framework = arduino
upload_port = /dev/tty.usbmodem11101
src_filter = -<*> +<../blank/>
