[env:l412kbu6]
platform = ststm32
board = nucleo_l412kb        ; STM32L412KBU6 (UFQFPN32) - 커스텀 보드
framework = stm32cube

upload_protocol = stlink
debug_tool = stlink

build_src_filter = +<*> -<hiz.c>   ; 메인 펌웨어 빌드 시 hiz.c 제외

build_flags =
    -O3                ; 최대 최적화 (속도 우선)
    -ffast-math        ; 부동소수점 빠른 연산

; 🦆 플래시 프로그래밍용 "핀 놓기" 펌웨어 (CH341A로 보드 플래시 쓸 때 MCU가 SPI 버스를 놓게 함)
[env:hiz]
platform = ststm32
board = nucleo_l412kb
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
build_src_filter = -<*> +<hiz.c>   ; hiz.c만 빌드
build_flags = -O2
